github:       [Repository metadata]
# baseurl:      https://webketje.com
timezone:     Europe/Brussels
encoding:     utf-8
title:        Webketje
permalink:    none
author:       Kevin Van Lierde
highlighter:  pygments
markdown:     kramdown
# Outputting
permalink:    /:categories/:title
# defaults:
# -
#    scope:
#     path: "about/blog"
#     type: "post"
#   values:
#     layout: "blog-post"
#     author: "Kevin Van Lierde"
# -