github: [Repository metadata]
timezone: Europe/Brussels
encoding: utf-8
title: webketje
permalink: none
author: Kevin Van Lierde
highlighter: pygments
markdown: kramdown
# Outputting
permalink: pretty
# defaults:
# -
#    scope:
#     path: "about/blog"
#     type: "post"
#   values:
#     layout: "blog-post"
#     author: "Kevin Van Lierde"
# -